### ISSUE TITLE
Warn about unexisting domain pot files?

### ISSUE THREAD

**Issue by gforcada** [collective/i18ndude#19]
I'm not sure how that should be handled... Let me explain it:

I have a distribution named ``freitag.foo`` a few templates have the appropiate ``i18n:domain="freitag.foo"`` but alas ... you copy and paste one template from distribution ``freitag.bar`` and when running ``find-untranslated`` it does not complain because everything is marked as it should, but then the strings on that template are not being translated.

OTOH this is not bad per se as it allows you to reuse, say plone translations, but maybe that's not what you really want...

Any ideas?

**Comment by mauritsvanrees** [comment]
I think find-untranslated should not care about the domain. Standard use case would indeed be that you customize a Plone template: you don't want i18ndude to complain that there is no plone.pot file.

Possibly an extra command, like find-non-standard-domains, where you pass `mydomain` as argument and let it report any files that have `i18n:domain="something.else"`.  But that is basically the same as `grep -r i18n:domain . | grep -v mydomain`, which I would then prefer.

**Comment by gforcada** [comment]
Fair enough.
