### ISSUE TITLE
Use chameleon if available

### ISSUE THREAD

**Issue by gforcada** [collective/i18ndude#21]
By default i18ndude extracts its messages through ``zope.tal``.

(Un)fortunately Plone 5 is moving to ``Chameleon``, so what will work perfectly on production and tests can possibly not work on i18ndude.

It just happened to me: I made an internal release of ``Chameleon`` with the ``i18n:ignore`` added on it and tests and production work perfectly but as I did not make a ``zope.tal`` internal release as well it still complains about them.

Unfortunately this ``five.pt``, ``z3c.pt`` and ``Chameleon`` provide a drop-in replacement for ``zope.tal`` but it's not exactly a 1:1 translation of code, so I'm not sure how easy it would be to make them exchangeable (if possible at all).

**Comment by mauritsvanrees** [comment]
Mostly this seems fixed with pull requests #26 and #27.

But letting i18ndude use the parsers of chameleon would be nice. And probably hard.

**Comment by gforcada** [comment]
@mauritsvanrees you end up using lxml right? So there's no real benefit of adding yet another xml parser, right? Closing it as I guess this is moot now.
