### ISSUE TITLE
Support Chameleon syntax

### ISSUE THREAD

**Issue by petri** [collective/i18ndude#36]
i18ndude barfs for example when Chameleon tuple unpacking is used:

`TALError: invalid repeat syntax: '(start,end) view/dayslots', at line 33, column 22, in file ../browser/slotsview.pt`

Given Plone5 uses Chameleon by default, fully supporting it in 18ndude would be nice.

**Comment by petri** [comment]
Sylvain has written an excellent piece on the differences:

http://www.boureliou.com/technoblog/blog/2009/chameleon.zpt-versus-standard-zope-page-templates

**Comment by gforcada** [comment]
I'm starting to enjoy using ``<p>${context/description}</p>`` rather than ``<p tal:content="context/description">DESCRIPTION</p>`` but as we have i18ndude integrated via plone.recipe.codeanalysis it is reporting lots of false positives... :-/

**Comment by mauritsvanrees** [comment]
Yes, supporting it would be good.

**Comment by Netroxen** [comment]
It's not overly pretty, but I've added a small check in https://github.com/collective/i18ndude/pull/41 which should temporarily fix linting tags with Chameleon syntax in them.

**Comment by mauritsvanrees** [comment]
I have released 4.2 which contains a partial fix, as mentioned by @Netroxen.
The `TALError: invalid repeat syntax` will still be there if you use tuple unpacking. I have not looked at that.

**Comment by Netroxen** [comment]
Looks good, nice to see it get merged! +1

**Comment by mauritsvanrees** [comment]
I have released `i18ndude 4.3` which supports the Chameleon repeat syntax.

@vincentfretin: It should be safe to use this repeat syntax in core Plone now.

**Comment by mauritsvanrees** [comment]
Since 2017 we had a fix for the Chameleon unpacking syntax in repeat statements, but not yet for the define statement. I ran across that in a client project today, so I fixed it. See https://github.com/collective/i18ndude/pull/90.
