### ISSUE TITLE
How to ignore more than one attribute?

### ISSUE THREAD

**Issue by krissik** [collective/i18ndude#37]
I have a simple page template that looks like that.

```html
...
      <h2 i18n:ignore="">${view/welcome_text}</h2>
      <img src="${view/image_url}"
           alt="${view/image_caption}"
           title="${view/image_caption}"
           i18n:ignore-attributes="alt title"
           />
...
```

As you see I would like to ignore title and alt attribute of the img tag. But it does not work as expected - i18ndude says:

```
...
-ERROR- - title attribute of <img> lacks i18n:attributes
...
-ERROR- - alt attribute of <img> lacks i18n:attributes
```

If I change i18n:ignore-attributes to  `i18n:ignore-attributes="title"` i18ndude only complains about missing "alt" attribute. 

How can I ignore both attributes?

(I have installed i18ndude-4.0.1 and zope.tal-4.2.0)

**Comment by frisi** [comment]
afaict i18ndude will not try to extract messageids for your alt or title tag at all.

you either tell zope to translate attributes (and i18ndude will extract them to the pot file):
```
      <img src="${view/image_url}"
           alt="translate me"
           title="translate me too"
           i18n:attributes="alt title"
           />
```

or you don't (zope won't try to translate, i18ndude won't extract):

```
      <img src="${view/image_url}"
           alt="${view/image_caption}"
           title="${view/image_caption}"
           />
```

**Comment by krissik** [comment]
If I do not have "i18n:attributes" attribute on my image tag `i18ndude find-untranslated` complains that they are not translated:

```
-ERROR- - *title* attribute of <img> lacks i18n:attributes
...
-ERROR- - *alt* attribute of <img> lacks i18n:attributes
```

The help message of i18ndude says that I can use i18n:ignore-attributes:

```
 bin/i18ndude find-untranslated --help
...
 You can mark tags to be ignored for this translation check by
    setting the "i18n:ignore" attribute on the tag. Same for
    attributes with "i18n:ignore-attributes".
```

With one attribute it works as expected - but two are not working.

Background: I would like to run `bin/code-analysis-find-untranslated` (see: https://github.com/plone/plone.recipe.codeanalysis - which calls `i18ndude find-untranslated`) on Jenkins so that I will be warned if I forget about internationalization.

**Comment by frisi** [comment]
ah - I see @krissik. never used `i18ndude find-untranslated`. good luck ;-)

**Comment by AnneGilles** [comment]
The solution is to list the attributes to be ignored separated by semicolon without spaces: **"alt;title"**

```xml
    <img src="${view/image_url}"
           alt="${view/image_caption}"
           title="${view/image_caption}"
           i18n:ignore-attributes="alt;title"
           />
```
