### ISSUE TITLE
How do you handle merge hell using i18ndude?

### ISSUE THREAD

**Issue by idgserpro** [collective/i18ndude#74]
We're doing development in a specific package where each developer is doing it's development in a different branch and after validating is integrated into master.

But we have multiple branches and multiple .pot editing using i18ndude and `rebuild_i18n-sh` from https://github.com/collective/buildout.plonetest/blob/master/qa.cfg and having a lot of merge conflicts since `i18ndude` changes a lot in the files.

Just out of curiosity, how do you handle merge conflicts using i18ndude? I'm sure you may have come across the same scenario here.

**Comment by mauritsvanrees** [comment]
If possible: do not run `i18ndude` on a feature branch. Do that only on master. Or do it on a short-lived branch if you want to do everything with PRs.

For the `.po` files, best is probably the `trmerge` command. For a single .po file:

- Copy the .po file from the master branch to `master.po`.
- Copy the .po file from the feature branch to `feature.po`.
- Run `i18ndude trmerge feature.po master.po > new.po`.
- Use `new.po` as the new .po file.
- Do an `i18ndude sync` afterwards, and you should be good to go.

Depending on your situation, it may be better to switch `feature.po` and `master.po`: a translation in the first one will get overwritten by a translation for the same message id from the second one. Or see if some of the options (`--ignore-extra` and `--no-override`) help you.

For the main `.pot` file, I would just regenerate it on master with `rebuild-pot`. Possibly you could use `i18ndude merge` in much the same way as `trmerge` above, but I don't think it is very useful here.

Does this help?

**Comment by idgserpro** [comment]
Thank you very much for the whole explanation. Since this is mainly a development question we'll close the issue. If new problems arise we may post here again.
