### ISSUE TITLE
Accept <div> inside <a>

### ISSUE THREAD

**Issue by pnicolli** [collective/i18ndude#78]
While going through some templates I got this error:
``OpenTagError: Tag <div> is not allowed in <a>``

I don't like having a ``div`` inside an ``a`` element, but in real life we get this from time to time. HTML5 allows it, so I would say we should not make this an error.

**Comment by mauritsvanrees** [comment]
Since this error is raised in zope.tal, I suggest opening an issue there. I don't think we can work around it here.
